stages:
  - publish
  - deploy

mirror:
  stage: publish
  script:
    - chmod +x ./ci/mirror.sh
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

deploy:
  stage: deploy
  script:
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
  only:
    - /^(main).*$/
  tags:
    - web
